### PR TITLE
feat: Support for sending files

### PR DESCRIPTION
**Pull request by Abadulrehman**

### CODE REVIEW

**Comment by assemmarwan** [comment]
@Abadulrehman What do you think about having another function where you can send file + message?

**Comment by Abadulrehman** [comment]
> @Abadulrehman What do you think about having another function where you can send file + message?

@assemmarwan If you mean a message that shows up together with the file, I think that is impossible because Telegram does not support sending files + message together. If you mean sending a file and then a message, then can't we just use "send_message" followed by "send_file"?

**Comment by assemmarwan** [comment]
> > @Abadulrehman What do you think about having another function where you can send file + message?
> 
> @assemmarwan If you mean a message that shows up together with the file, I think that is impossible because Telegram does not support sending files + message together. If you mean sending a file and then a message, then can't we just use "send_message" followed by "send_file"?

Yes that's what I meant a function that calls these two 😅.

**Comment by Abadulrehman** [comment]
> > > @Abadulrehman What do you think about having another function where you can send file + message?
> > 
> > 
> > @assemmarwan If you mean a message that shows up together with the file, I think that is impossible because Telegram does not support sending files + message together. If you mean sending a file and then a message, then can't we just use "send_message" followed by "send_file"?
> 
> Yes that's what I meant a function that calls these two sweat_smile.

> @assemmarwan If you mean a message that shows up together with the file, I think that is impossible because Telegram does not support sending files + message together.

@assemmarwan My mistake, it actually does. Added it to our wrapper.

**Review by assemmarwan — APPROVED** [review]

**Pull request merged**
